services:
  mysql:
    image: mysql:latest  
    container_name: book-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: bookdb
      MYSQL_USER: user1
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  adminer:
    image: adminer:latest
    container_name: adminer-ui-book
    environment:
      ADMINER_DEFAULT_SERVER: book-db
    ports:
      - "8081:8080"
    networks:
      - backend
    depends_on:
      - mysql

volumes:
  mysql_data:

networks:
  backend:
    driver: bridge

